typography_spectrum: 0.6576728
color:
  saturation: 0.02150086
  brandStrength: 0.7192243
  lightness: 0.4331115
  rhythmicContrast: 0.689788
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.3279932
name: Reinerlab
navigation:
  - name: Technologies of the Extended Mind
    url: 'http://peterbartreiner.com/technologies-of-the-extended-mind/'
    type: external
title: ReinerLab
